#!/bin/bash

set -e

update_readme() {
  OLD_README="$(cat README.md)"

  ed README.md <<- EOF
/Documentation
+2kb
/##
'b,-2c
$(printf -- "$OUTPUT" | sort)
.
w
q
EOF
}

go get github.com/davecheney/godoc2md
export OUTPUT=$(godoc2md . | ghead -n -10 | gtail -n +15)
update_readme

