version: 2
jobs:
  build:
    working_directory: /go/src/github.com/sheerun/yson
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: go get
      - run: go test -bench=. -benchmem
